export interface LanguageStore  {
    lang: string;
    t: {
        home:string,
        login:string,
        signup:string,
        logout:string,
        greeting: string;
        title:string;
        cart:string;
        addToCart: string;
        checkout: string;
        profile: string;
        createAccount:string;
        loginTitle: string;
        password:string;
        yourName:string;
        fullName:string;
        confirmPassword:string;
        alreadyHaveAccount:string;
        noAccount:string;
        loginHere:string;
        signupHere:string;
        searchText:string;
        startLive:string,
        stopLive:string,
        loading:string;
        dashboard:string;
        editProduct:string;
        category:string;
        productName:string;
        pickSize:string;
        chooseQuantity:string;
        noProductsFound:string;
        emptyCart:string;
        emptyCartTitle:string;
        letBuy:string;
        checkOut:string;
        alsoBought:string;
        haveCouponCode:string;
        enterCode:string;
        signupSuccess:string;
        loginSuccess:string;
        logoutSuccess:string;
        logoutFailed:string;
        signupFailed:string;
        wrongPassword:string;
        invalid:string;
        adminDashboard:string;
        createProduct:string;
        descriptionProduct:string;
        products:string;
        featured:string;
        actions:string;
        sizePlaceholder:string;
        uploadImage:string;
        analytic:string;
        videoConsole:string;
        totalUsers:string;
        totalProducts:string;
        totalSales:string;
        totalRevenues:string;
        sales:string;
        revenue:string;
        processing:string;
        orderSummary:string;
        price:string;
        originalPrice:string;
        total:string;
        subTotal:string;
        savings:string;
        continueShopping:string;
        applyCode:string;
        deleteProductText:string;
        cancel:string;
        delete:string;
        purchaseCancel:string;
        purchaseCancelTitle:string;
        purchaseCancelContact:string;
        returnHome:string;
        liveStreamTitle:string;
        liveStreamTime:string;
        startRecord:string;
        stopRecord:string;
        micOn:string;
        micOff:string;
        previewVideo:string;
        titleVideo:string;
        missingTitle:string;
        descriptionVideo:string;
        uploadVideo:string;
        discardVideo:string;
        alertDiscardVideo:string;
        uploadSuccess:string;
        loadingUploadVideo:string;
        save:string;
        createGift:string;
        room:string;
        updateSuccess:string;
        updateFailed:string;
        changePassword_text:string;
        currentPassword_text:string;
        newPassword_text:string;

    };
    setLang: (lang: string) => void;
};